language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_script:
  - npm install -g gulp
  - npm i
deploy:
  provider: heroku
  api_key:
    secure: "fd8a69f4-8735-418a-9322-58b9530f1d61"
  app: reviewfy
    
